# Generated by Django 4.0.4 on 2022-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0010_authtoken_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='client',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
